import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
export default function Home() {
  return (
    <>
      <Head>
        <title>get your dream job| real fast</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/realfast logo.png" /> 
      </Head>
      <main>
        <nav className = {styles.nabar}>
          <ul className={styles.}>
            <li className>
              <span>real fast</span>
              <Image width={38} height={38} src='/realfast_logo.png' />
            </li>
            <li>
            <Link href='#'>find jobs</Link>
            </li>
            <ul>
              <ul></ul>
            </ul>
          </ul>
        </nav>
      </main>
    </>
  )









const styles = {
  nabar:'h-[60px] flex flex-row justify-between items-center px-3 border border-gray-200 shadow-md',
  
}


  
}
